# Generated by Django 3.1.2 on 2020-10-08 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CuratedLists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Curation',
        ),
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.TextField(default='password'),
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
        ),
    ]
