# Generated by Django 3.1.2 on 2020-10-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuratedLists', '0002_auto_20201008_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curation',
            name='blogs',
        ),
        migrations.RemoveField(
            model_name='curation',
            name='books',
        ),
        migrations.RemoveField(
            model_name='curation',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='curation',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='curation',
            name='videos',
        ),
        migrations.AddField(
            model_name='curation',
            name='data',
            field=models.JSONField(default='empty'),
        ),
    ]
