# Generated by Django 3.1.2 on 2020-10-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuratedLists', '0003_auto_20201008_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
